#!/usr/bin/env -S python -O
'''
Bibed — main application launcher
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Should installed or linked in :path:`/usr/bin`, or anywhere executable
programs live.

..  This file is part of the Bibed program.

    Bibed is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as
    published by the Free Software Foundation, version 3.

    Bibed is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public
    License version 3 along with Bibed. If not, see
    https://www.gnu.org/licenses/gpl-3.0.html

:copyright:
        * 2019 Olivier Cortès <olive@cocoliv.es>
        * 2019 Collectif Cocoliv.es <contact@cocoliv.es>

:license: GNU GPL version 3

'''


if __name__ == '__main__':
    from bibed.main import app_main
    app_main()
